[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pdf2docx>=0.5.8",
    "pymupdf>=1.25.5",
    "python-docx>=1.1.2",
]
